{
 "title": "Mesos: Agents Summary",
 "description": "Show Mesos Agent metrics on a host",
 "tags": [
  "mesos",
  "agents",
  "summary",
  "dc/os"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mesos_slave_uptime_secs, host)"
   },
   {
    "name": "rate",
    "label": "Rate Interval",
    "query": "1s,5s,10s,30s,1m,5m,15m,30m,1h,2h,6h,1d,7d"
   }
  ]
 },
 "panels": [
  { "title": "Basic: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_uptime_secs{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Mesos Agent Uptime",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "content": "Shows the time in seconds since the last restart of the Mesos agent.\n\nThis metric should always increase. If the metric drops to zero, the agent has restarted.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Registered",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_registered{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Registered",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "content": "Whether this agent is registered with a master.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Error Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_recovery_errors{host=~\"$host\"}[$rate]))",
     "legendFormat": "On agent recovery"
    },
    {
     "expr": "sum(irate(mesos_slave_container_launch_errors{host=~\"$host\"}[$rate]))",
     "legendFormat": "On container launch"
    },
    {
     "expr": "sum(irate(mesos_slave_invalid_status_updates{host=~\"$host\"}[$rate]))",
     "legendFormat": "For status updates"
    },
    {
     "expr": "sum(irate(mesos_slave_invalid_framework_messages{host=~\"$host\"}[$rate]))",
     "legendFormat": "For framework messages"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "content": "Number of errors encountered per second, measured over $rate interval windows.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Resources Summary: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "% of Allocated Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_cpus_percent{host=~\"$host\"})",
     "legendFormat": "CPUs"
    },
    {
     "expr": "sum(mesos_slave_mem_percent{host=~\"$host\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(mesos_slave_disk_percent{host=~\"$host\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(mesos_slave_gpus_percent{host=~\"$host\"})",
     "legendFormat": "GPUs"
    }
   ]
  },
  {
   "title": "% of Allocated Resources",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "content": "Percentage of allocated or offered resources.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Resources Detailed: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_cpus_total{host=~\"$host\"} + mesos_slave_cpus_revocable_total{host=~\"$host\"})",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(mesos_slave_cpus_used{host=~\"$host\"})",
     "legendFormat": "Offered or Allocated CPUs"
    },
    {
     "expr": "sum(irate(cpus_system_time_secs{host=~\"$host\"}[$rate]) + irate(cpus_user_time_secs{host=~\"$host\"}[$rate])) * sum(mesos_slave_cpus_total{host=~\"$host\"})",
     "legendFormat": "Containers CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Allocation and Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "content": "Number of CPUs in total and offered or allocated within the cluster. Additionally shows the percentage of total CPUs used by the container subsystem.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Memory Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_mem_total{host=~\"$host\"} + mesos_slave_mem_revocable_total{host=~\"$host\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(mesos_slave_mem_used{host=~\"$host\"})",
     "legendFormat": "Offered or Allocated Memory"
    },
    {
     "expr": "sum(mem_total_bytes{host=~\"$host\"}) / 1000000",
     "legendFormat": "Containers Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Allocation and Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "content": "Memory in total and offered or allocated within the cluster. Additionally shows the amount of memory used by containers.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "GPU Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_gpus_total{host=~\"$host\"} + mesos_slave_gpus_revocable_total{host=~\"$host\"})",
     "legendFormat": "Total GPUs"
    },
    {
     "expr": "sum(mesos_slave_gpus_used{host=~\"$host\"})",
     "legendFormat": "Offered or Allocated GPUs"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "content": "Number of GPUs in total and offered or allocated within the cluster.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Disk Allocation and Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_disk_total{host=~\"$host\"} + mesos_slave_disk_revocable_total{host=~\"$host\"})",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(mesos_slave_disk_used{host=~\"$host\"})",
     "legendFormat": "Offered of Allocated Disk"
    },
    {
     "expr": "sum(disk_used_bytes{host=~\"$host\"}) / 1000000",
     "legendFormat": "Container Disk Usage"
    }
   ]
  },
  {
   "title": "Disk Allocation",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "content": "Disk space in total and offered or allocated within the cluster. Additionally shows the amount of disk space used by containers.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Executors: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Active Executors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_executors_registering{host=~\"$host\"})",
     "legendFormat": "Registering"
    },
    {
     "expr": "sum(mesos_slave_executors_running{host=~\"$host\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(mesos_slave_executors_terminating{host=~\"$host\"})",
     "legendFormat": "Terminating"
    }
   ]
  },
  {
   "title": "Active Executors",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "content": "Number of executors in an active state.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Terminal Executors Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_executors_terminated{host=~\"$host\"}[$rate]))",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(irate(mesos_slave_executors_preempted{host=~\"$host\"}[$rate]))",
     "legendFormat": "Preempted"
    }
   ]
  },
  {
   "title": "Terminal Executors Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "content": "Rate of executors terminated per second, measured over $rate interval windows.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Tasks: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mesos_slave_tasks_staging{host=~\"$host\"})",
     "legendFormat": "Staging"
    },
    {
     "expr": "sum(mesos_slave_tasks_starting{host=~\"$host\"})",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(mesos_slave_tasks_running{host=~\"$host\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(mesos_slave_tasks_killing{host=~\"$host\"})",
     "legendFormat": "Killing"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "content": "Number of tasks in an active state.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Terminal Tasks Rate ($rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mesos_slave_tasks_finished{host=~\"$host\"}[$rate]))",
     "legendFormat": "Finished"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_failed{host=~\"$host\"}[$rate]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_gone{host=~\"$host\"}[$rate]))",
     "legendFormat": "Gone"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_killed{host=~\"$host\"}[$rate]))",
     "legendFormat": "Killed"
    },
    {
     "expr": "sum(irate(mesos_slave_tasks_lost{host=~\"$host\"}[$rate]))",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "Terminal Tasks Rate",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "content": "Rate of tasks terminated per second, measured over 1h interval windows.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  { "title": "Mesos Agent Process: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(procstat_cpu_usage{process_name=\"mesos-agent\", host=~\"$host\"})",
     "legendFormat": "mesos-agent"
    }
   ]
  },
  {
   "title": "Used Percent of Total CPU",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "content": "The percentage of time that the \"mesos-agent\" process is active in any capacity.\n\nTODO(tillt): Add expectation and interpretation hints."
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(procstat_memory_rss{process_name=\"mesos-agent\",host=~\"$host\"})",
     "legendFormat": "mesos-agent"
    }
   ]
  },
  {
   "title": "Memory (RSS) Usage",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "content": "The amount of real memory (resident set) that the \"mesos-agent\" process is using.\n\nTODO(tillt): Add expectation and interpretation hints."
  }
 ]
}